name: financial_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  intl: ^0.20.2
  auto_route: ^10.0.1
  syncfusion_flutter_charts: ^29.1.35
  custom_sliding_segmented_control: ^1.8.5
  path_provider: ^2.1.5
  grouped_list: ^6.0.0
  freezed_annotation: ^3.0.0
  rxdart: ^0.28.0
  auto_size_text: ^3.0.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  auto_route_generator: ^10.0.1
  freezed: ^3.0.6
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

flutter:
  uses-material-design: true
